package puma.sp.clients;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "AttributeForwardImplService", targetNamespace = "http://services.proxy.puma/", wsdlLocation = "http://localhost:8080/PUMA-Proxy/AttributeForwardService?wsdl")
public class AttributeForwardImplService
    extends Service
{

    private final static URL ATTRIBUTEFORWARDIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATTRIBUTEFORWARDIMPLSERVICE_EXCEPTION;
    private final static QName ATTRIBUTEFORWARDIMPLSERVICE_QNAME = new QName("http://services.proxy.puma/", "AttributeForwardImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PUMA-Proxy/AttributeForwardService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATTRIBUTEFORWARDIMPLSERVICE_WSDL_LOCATION = url;
        ATTRIBUTEFORWARDIMPLSERVICE_EXCEPTION = e;
    }

    public AttributeForwardImplService() {
        super(__getWsdlLocation(), ATTRIBUTEFORWARDIMPLSERVICE_QNAME);
    }

    public AttributeForwardImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AttributeForwardService
     */
    @WebEndpoint(name = "AttributeForwardImplPort")
    public AttributeForwardService getAttributeForwardImplPort() {
        return super.getPort(new QName("http://services.proxy.puma/", "AttributeForwardImplPort"), AttributeForwardService.class);
    }

    private static URL __getWsdlLocation() {
        if (ATTRIBUTEFORWARDIMPLSERVICE_EXCEPTION!= null) {
            throw ATTRIBUTEFORWARDIMPLSERVICE_EXCEPTION;
        }
        return ATTRIBUTEFORWARDIMPLSERVICE_WSDL_LOCATION;
    }

}