package puma.sp.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AttributeForwardService", targetNamespace = "http://puma.com/proxy")
public interface AttributeForwardService {


    /**
     * 
     * @param context
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "send", targetNamespace = "http://puma.com/proxy", className = "com.puma.proxy.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://puma.com/proxy", className = "com.puma.proxy.SendResponse")
    public String send(
        @WebParam(name = "context", targetNamespace = "")
        String context);

}