
package be.kuleuven.cs.projects.samples.up.document_sending_service.clients;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccessControlImplService", targetNamespace = "http://services.sp.puma/", wsdlLocation = "http://localhost:8080/PUMA-war/AccessControlService?wsdl")
public class AccessControlImplService
    extends Service
{

    private final static URL ACCESSCONTROLIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCESSCONTROLIMPLSERVICE_EXCEPTION;
    private final static QName ACCESSCONTROLIMPLSERVICE_QNAME = new QName("http://services.sp.puma/", "AccessControlImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PUMA-war/AccessControlService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCESSCONTROLIMPLSERVICE_WSDL_LOCATION = url;
        ACCESSCONTROLIMPLSERVICE_EXCEPTION = e;
    }

    public AccessControlImplService() {
        super(__getWsdlLocation(), ACCESSCONTROLIMPLSERVICE_QNAME);
    }

    public AccessControlImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCESSCONTROLIMPLSERVICE_QNAME, features);
    }

    public AccessControlImplService(URL wsdlLocation) {
        super(wsdlLocation, ACCESSCONTROLIMPLSERVICE_QNAME);
    }

    public AccessControlImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCESSCONTROLIMPLSERVICE_QNAME, features);
    }

    public AccessControlImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccessControlImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccessControlService
     */
    @WebEndpoint(name = "AccessControlImplPort")
    public AccessControlService getAccessControlImplPort() {
        return super.getPort(new QName("http://services.sp.puma/", "AccessControlImplPort"), AccessControlService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccessControlService
     */
    @WebEndpoint(name = "AccessControlImplPort")
    public AccessControlService getAccessControlImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.sp.puma/", "AccessControlImplPort"), AccessControlService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCESSCONTROLIMPLSERVICE_EXCEPTION!= null) {
            throw ACCESSCONTROLIMPLSERVICE_EXCEPTION;
        }
        return ACCESSCONTROLIMPLSERVICE_WSDL_LOCATION;
    }

}
