package puma.proxy.clients;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AttributeQueryImplService", targetNamespace = "http://services.idp.puma/", wsdlLocation = "http://localhost:8080/PUMA-IdP/AttributeQueryService?wsdl")
public class AttributeQueryImplService
    extends Service
{

    private final static URL ATTRIBUTEQUERYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATTRIBUTEQUERYIMPLSERVICE_EXCEPTION;
    private final static QName ATTRIBUTEQUERYIMPLSERVICE_QNAME = new QName("http://services.idp.puma/", "AttributeQueryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PUMA-IdP/AttributeQueryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATTRIBUTEQUERYIMPLSERVICE_WSDL_LOCATION = url;
        ATTRIBUTEQUERYIMPLSERVICE_EXCEPTION = e;
    }

    public AttributeQueryImplService() {
        super(__getWsdlLocation(), ATTRIBUTEQUERYIMPLSERVICE_QNAME);
    }

    public AttributeQueryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATTRIBUTEQUERYIMPLSERVICE_QNAME, features);
    }

    public AttributeQueryImplService(URL wsdlLocation) {
        super(wsdlLocation, ATTRIBUTEQUERYIMPLSERVICE_QNAME);
    }

    public AttributeQueryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATTRIBUTEQUERYIMPLSERVICE_QNAME, features);
    }

    public AttributeQueryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AttributeQueryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AttributeQueryService
     */
    @WebEndpoint(name = "AttributeQueryImplPort")
    public AttributeQueryService getAttributeQueryImplPort() {
        return super.getPort(new QName("http://services.idp.puma/", "AttributeQueryImplPort"), AttributeQueryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AttributeQueryService
     */
    @WebEndpoint(name = "AttributeQueryImplPort")
    public AttributeQueryService getAttributeQueryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.idp.puma/", "AttributeQueryImplPort"), AttributeQueryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATTRIBUTEQUERYIMPLSERVICE_EXCEPTION!= null) {
            throw ATTRIBUTEQUERYIMPLSERVICE_EXCEPTION;
        }
        return ATTRIBUTEQUERYIMPLSERVICE_WSDL_LOCATION;
    }

}