package puma.proxy.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import puma.proxy.clients.resources.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AttributeQueryService", targetNamespace = "http://puma/idp")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AttributeQueryService {


    /**
     * 
     * @param context
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://puma/idp", className = "puma.proxy.clients.resources.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://puma/idp", className = "puma.proxy.clients.resources.QueryResponse")
    @Action(input = "http://puma/idp/AttributeQueryService/queryRequest", output = "http://puma/idp/AttributeQueryService/queryResponse")
    public String query(
        @WebParam(name = "context", targetNamespace = "")
        String context);

}